# Generated by Django 2.2 on 2020-09-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(db_column='username')),
                ('password', models.TextField(db_column='password')),
                ('originalpassword', models.TextField(db_column='originalpassword')),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
