# Generated by Django 2.2 on 2020-09-15 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
